dbt_pipeline:
  target: dev
  outputs:
    dev:
      type: duckdb
      # Chemin vers la base DuckDB créée par ingest.py
      # Le chemin est relatif au répertoire dbt_pipeline/
      path: "../pipeline/ventes.duckdb"
      threads: 1
